image: docker

services:
  - docker:19.03.1-dind

build:
  stage: build
  variables:
    IMG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t ${IMG} .
    - docker push ${IMG}
